### ISSUE TITLE
v0.3 checklist

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/twofactor_webauthn#110]
* [x] https://github.com/nextcloud/twofactor_webauthn/issues/78
* [x] https://github.com/nextcloud/twofactor_webauthn/issues/77
* [x] https://github.com/nextcloud/twofactor_webauthn/issues/5
* [x] https://github.com/nextcloud/twofactor_webauthn/issues/99
* [x] https://github.com/nextcloud/twofactor_webauthn/issues/6
* [x] #112
* [x] #111
* [x] https://github.com/nextcloud/twofactor_webauthn/issues/121
